[animation]
enabled       =   true
duration_ms   =   150
curve         =   "easeout"

[animation.windows_in]
enabled       =   true
duration_ms   =   200
curve         =   "easeout"
style         =   "none"
shader        =   "shaders/roll-drop.glsl"

[animation.windows_out]
enabled       =   true
duration_ms   =   150
curve         =   "easeout"
style         =   "slide"

[animation.windows_move]
enabled       =   true
duration_ms   =   150
curve         =   "snappy"
shader        =   "shaders/squash.glsl"

[animation.workspaces]
enabled       =   true
duration_ms   =   150
curve         =   "easeout"

[animation.overview]
enabled       =   true
duration_ms   =   150
curve         =   "easeout"

[animation.scratchpad]
enabled       =   false
duration_ms   =   150
curve         =   "easeout"
dim           =   0.5
blur          =   false
scale         =   0.0
maximize      =   false
fullscreen    =   false

[animation.border]
enabled       =   true
duration_ms   =   150
curve         =   "easeout"

[animation.dim_unfocused]
enabled       =   false
duration_ms   =   250
curve         =   "easeout"
dim           =   0.0

[animation.layers]
enabled       =   false
duration_ms   =   250
curve         =   "easeout"
