[include]
files = [
    "cfg/animations.toml",
    "cfg/appearance.toml",
    "cfg/general.toml",
    "cfg/input.toml",
    "cfg/keybinds.toml",
    "cfg/layer-rules.toml",
    "cfg/layout.toml",
    "cfg/output.toml",
    "cfg/window-rules.toml",
    "noctalia.toml",
]
