# Blur all windows
[[window_rule]]
blur             =   true
blur_optimized   =   true

# Open a specific app maximized
[[window_rule]]
match.app_id     =   "^discord$|^vesktop$|^codium$|^firefox$|^brave-browser$|^brave-origin$|zen|^com.github.th_ch.youtube_music$"
default_width    =   1.0
default_height   =   1.0

# Open a specific app maximized to edges
[[window_rule]]
match.app_id                =   "Minecraft*|^org.vinegarhq.Sober$"
default_maximize_to_edges   =   true

# Blur specific windows
[[window_rule]]
match.app_id        =   "^nemo$|^xarchiver$"
opacity             =   0.9
blur                =   true
blur_optimized      =   true

# Fix Zen browser transparency
[[window_rule]]
match.app_id        =   "^zen$"
opacity             =   0.999
blur                =   true
blur_optimized      =   true

# Open Zen picture-in-picture mode as floating
[[window_rule]]
match.app_id        =   "zen"
match.title         =   "^Picture-in-Picture$"
default_floating    =   true
default_focused     =   false
focus_on_activate   =   true
default_width       =   0.4
default_height      =   0.413
default_position    =   { x = 20, y = 20, anchor = "bottom_right" }

[[window_rule]]
match.app_id       =   "^dev.noctalia.Noctalia$"
default_floating   =   true
default_size       =   [1020, 900]

[[window_rule]]
match.app_id       =   "^dev.noctalia.UmbrielSharePicker$"
default_floating   =   true
default_size       =   [800, 600]
